Countries=[
("Afghanistan ","Afghanistan "),
("Albania ","Albania "),
("Algeria ","Algeria "),
("American Samoa ","American Samoa "),
("Andorra ","Andorra "),
("Angola ","Angola "),
("Anguila ","Anguila "),
("Antigua and Barbuda ","Antigua and Barbuda "),
("Argentina ","Argentina "),
("Armenia ","Armenia "),
("Aruba ","Aruba "),
("Australia ","Australia "),
("Austria ","Austria "),
("Azerbaijan ","Azerbaijan "),
("Bahamas, The ","Bahamas, The "),
("Bahrain ","Bahrain "),
("Bangladesh ","Bangladesh "),
("Barbados ","Barbados "),
("Belarus ","Belarus "),
("Belgium ","Belgium "),
("Belgium-Luxembourg ","Belgium-Luxembourg "),
("Belize ","Belize "),
("Benin ","Benin "),
("Bermuda ","Bermuda "),
("Bhutan ","Bhutan "),
("Bolivia ","Bolivia "),
("Bosnia and Herzegovina ","Bosnia and Herzegovina "),
("Botswana ","Botswana "),
("Br. Antr. Terr ","Br. Antr. Terr "),
("Brazil ","Brazil "),
("British Indian Ocean Ter. ","British Indian Ocean Ter. "),
("British Virgin Islands ","British Virgin Islands "),
("Brunei ","Brunei "),
("Bulgaria ","Bulgaria "),
("Burkina Faso ","Burkina Faso "),
("Burundi ","Burundi "),
("Cambodia ","Cambodia "),
("Cameroon ","Cameroon "),
("Canada ","Canada "),
("Cape Verde ","Cape Verde "),
("Cayman Islands ","Cayman Islands "),
("Central African Republic ","Central African Republic "),
("Chad ","Chad "),
("Chile ","Chile "),
("China ","China "),
("Christmas Island ","Christmas Island "),
("Cocos (Keeling) Islands ","Cocos (Keeling) Islands "),
("Colombia ","Colombia "),
("Comoros ","Comoros "),
("Congo, Dem. Rep. ","Congo, Dem. Rep. "),
("Congo, Rep. ","Congo, Rep. "),
("Cook Islands ","Cook Islands "),
("Costa Rica ","Costa Rica "),
("Cote d'Ivoire ","Cote d'Ivoire "),
("Croatia ","Croatia "),
("Cuba ","Cuba "),
("Cyprus ","Cyprus "),
("Czech Republic ","Czech Republic "),
("Czechoslovakia ","Czechoslovakia "),
("Denmark ","Denmark "),
("Djibouti ","Djibouti "),
("Dominica ","Dominica "),
("Dominican Republic ","Dominican Republic "),
("East Timor ","East Timor "),
("Ecuador ","Ecuador "),
("Egypt, Arab Rep. ","Egypt, Arab Rep. "),
("El Salvador ","El Salvador "),
("Equatorial Guinea ","Equatorial Guinea "),
("Eritrea ","Eritrea "),
("Estonia ","Estonia "),
("Ethiopia (excludes Eritrea) ","Ethiopia (excludes Eritrea) "),
("Ethiopia (includes Eritrea) ","Ethiopia (includes Eritrea) "),
("European Union ","European Union "),
("Faeroe Islands ","Faeroe Islands "),
("Falkland Island ","Falkland Island "),
("Fiji ","Fiji "),
("Finland ","Finland "),
("Fm Panama Cz ","Fm Panama Cz "),
("Fm Rhod Nyas ","Fm Rhod Nyas "),
("Fm Tanganyik ","Fm Tanganyik "),
("Fm Vietnam Dr ","Fm Vietnam Dr "),
("Fm Vietnam Rp ","Fm Vietnam Rp "),
("Fm Zanz-Pemb ","Fm Zanz-Pemb "),
("Fr. So. Ant. Tr ","Fr. So. Ant. Tr "),
("France ","France "),
("Free Zones ","Free Zones "),
("French Guiana ","French Guiana "),
("French Polynesia ","French Polynesia "),
("Gabon ","Gabon "),
("Gambia, The ","Gambia, The "),
("Gaza Strip ","Gaza Strip "),
("Georgia ","Georgia "),
("German Democratic Republic ","German Democratic Republic "),
("Germany ","Germany "),
("Ghana ","Ghana "),
("Gibraltar ","Gibraltar "),
("Greece ","Greece "),
("Greenland ","Greenland "),
("Grenada ","Grenada "),
("Guadeloupe ","Guadeloupe "),
("Guam ","Guam "),
("Guatemala ","Guatemala "),
("Guinea ","Guinea "),
("Guinea-Bissau ","Guinea-Bissau "),
("Guyana ","Guyana "),
("Haiti ","Haiti "),
("Holy See ","Holy See "),
("Honduras ","Honduras "),
("Hong Kong, China ","Hong Kong, China "),
("Hungary ","Hungary "),
("Iceland ","Iceland "),
("India ","India "),
("Indonesia ","Indonesia "),
("Iran, Islamic Rep. ","Iran, Islamic Rep. "),
("Iraq ","Iraq "),
("Ireland ","Ireland "),
("Israel ","Israel "),
("Italy ","Italy "),
("Jamaica ","Jamaica "),
("Japan ","Japan "),
("Jhonston Island ","Jhonston Island "),
("Jordan ","Jordan "),
("Kazakhstan ","Kazakhstan "),
("Kenya ","Kenya "),
("Kiribati ","Kiribati "),
("Korea, Dem. Rep. ","Korea, Dem. Rep. "),
("Korea, Rep. ","Korea, Rep. "),
("Kuwait ","Kuwait "),
("Kyrgyz Republic ","Kyrgyz Republic "),
("Lao PDR ","Lao PDR "),
("Latvia ","Latvia "),
("Lebanon ","Lebanon "),
("Lesotho ","Lesotho "),
("Liberia ","Liberia "),
("Libya ","Libya "),
("Liechtenstein ","Liechtenstein "),
("Lithuania ","Lithuania "),
("Luxembourg ","Luxembourg "),
("Macao ","Macao "),
("Macedonia, FYR ","Macedonia, FYR "),
("Madagascar ","Madagascar "),
("Malawi ","Malawi "),
("Malaysia ","Malaysia "),
("Maldives ","Maldives "),
("Mali ","Mali "),
("Malta ","Malta "),
("Marshall Islands ","Marshall Islands "),
("Martinique ","Martinique "),
("Mauritania ","Mauritania "),
("Mauritius ","Mauritius "),
("Mexico ","Mexico "),
("Micronesia, Fed. Sts. ","Micronesia, Fed. Sts. "),
("Midway Islands ","Midway Islands "),
("Moldova ","Moldova "),
("Monaco ","Monaco "),
("Mongolia ","Mongolia "),
("Montserrat ","Montserrat "),
("Morocco ","Morocco "),
("Mozambique ","Mozambique "),
("Myanmar ","Myanmar "),
("Namibia ","Namibia "),
("Nauru ","Nauru "),
("Nepal ","Nepal "),
("Netherlands ","Netherlands "),
("Netherlands Antilles ","Netherlands Antilles "),
("Neutral Zone ","Neutral Zone "),
("New Caledonia ","New Caledonia "),
("New Zealand ","New Zealand "),
("Nicaragua ","Nicaragua "),
("Niger ","Niger "),
("Nigeria ","Nigeria "),
("Niue ","Niue "),
("Norfolk Island ","Norfolk Island "),
("Northern Mariana Islands ","Northern Mariana Islands "),
("Norway ","Norway "),
("Oman ","Oman "),
("Pacific Islands ","Pacific Islands "),
("Pakistan ","Pakistan "),
("Palau ","Palau "),
("Panama ","Panama "),
("Papua New Guinea ","Papua New Guinea "),
("Paraguay ","Paraguay "),
("Pen Malaysia ","Pen Malaysia "),
("Peru ","Peru "),
("Philippines ","Philippines "),
("Pitcairn ","Pitcairn "),
("Poland ","Poland "),
("Portugal ","Portugal "),
("Puerto Rico ","Puerto Rico "),
("Qatar ","Qatar "),
("Reunion ","Reunion "),
("Romania ","Romania "),
("Russian Federation ","Russian Federation "),
("Rwanda ","Rwanda "),
("Ryukyu Is ","Ryukyu Is "),
("Sabah ","Sabah "),
("Saint Helena ","Saint Helena "),
("Saint Kitts-Nevis-Anguilla-Aru ","Saint Kitts-Nevis-Anguilla-Aru "),
("Saint Pierre and Miquelon ","Saint Pierre and Miquelon "),
("Samoa ","Samoa "),
("San Marino ","San Marino "),
("Sao Tome and Principe ","Sao Tome and Principe "),
("Sarawak ","Sarawak "),
("Saudi Arabia ","Saudi Arabia "),
("Senegal ","Senegal "),
("Seychelles ","Seychelles "),
("Sierra Leone ","Sierra Leone "),
("SIKKIM ","SIKKIM "),
("Singapore ","Singapore "),
("Slovak Republic ","Slovak Republic "),
("Slovenia ","Slovenia "),
("Solomon Islands ","Solomon Islands "),
("Somalia ","Somalia "),
("South Africa ","South Africa "),
("Soviet Union ","Soviet Union "),
("Spain ","Spain "),
("Special Categories ","Special Categories "),
("Sri Lanka ","Sri Lanka "),
("St. Kitts and Nevis ","St. Kitts and Nevis "),
("St. Lucia ","St. Lucia "),
("St. Vincent and the Grenadines ","St. Vincent and the Grenadines "),
("Sudan ","Sudan "),
("Suriname ","Suriname "),
("Svalbard and Jan Mayen Is ","Svalbard and Jan Mayen Is "),
("Swaziland ","Swaziland "),
("Sweden ","Sweden "),
("Switzerland ","Switzerland "),
("Syrian Arab Republic ","Syrian Arab Republic "),
("Taiwan ","Taiwan "),
("Tajikistan ","Tajikistan "),
("Tanzania ","Tanzania "),
("Thailand ","Thailand "),
("Togo ","Togo "),
("Tokelau ","Tokelau "),
("Tonga ","Tonga "),
("Trinidad and Tobago ","Trinidad and Tobago "),
("Tunisia ","Tunisia "),
("Turkey ","Turkey "),
("Turkmenistan ","Turkmenistan "),
("Turks and Caicos Isl. ","Turks and Caicos Isl. "),
("Tuvalu ","Tuvalu "),
("Uganda ","Uganda "),
("Ukraine ","Ukraine "),
("United Arab Emirates ","United Arab Emirates "),
("United Kingdom ","United Kingdom "),
("United States ","United States "),
("Unspecified ","Unspecified "),
("Uruguay ","Uruguay "),
("Us Msc.Pac.I ","Us Msc.Pac.I "),
("Uzbekistan ","Uzbekistan "),
("Vanuatu ","Vanuatu "),
("Venezuela ","Venezuela "),
("Vietnam ","Vietnam "),
("Virgin Islands (U.S.) ","Virgin Islands (U.S.) "),
("Wake Island ","Wake Island "),
("Wallis and Futura Isl. ","Wallis and Futura Isl. "),
("Western Sahara ","Western Sahara "),
("World ","World "),
("Yemen Democratic ","Yemen Democratic "),
("Yemen, Rep. ","Yemen, Rep. "),
("Yugoslavia ","Yugoslavia "),
("Yugoslavia, FR Serbia/Montene ","Yugoslavia, FR (Serbia/Montene "),
("Zambia ","Zambia "),
("Zimbabwe ","Zimbabwe "),
]